apiVersion: v1
kind: Service
metadata:
  name: gate
  labels:
    app: gate
spec:
  type: LoadBalancer
  ports:
  - port: 10009
    targetPort: 10009
    nodePort: {{ .Values.GateNodePort }}
    protocol: TCP
  selector:
    app: gate
