apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic
spec:
  selector:
    matchLabels:
      app: logic
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: logic
    spec:
      containers:
      - name: logic
        image: {{ .Values.FirestrikeServerDockerImage }}
        env:
        - name: SERVER_TYPE
          value: "logic"
        - name: LOGIC_LISTEN_PORT
          value: "1339"
        - name: NODE_MGR_HOST
          value: "{{ .Values.NodemgrHost }}"
        - name: NODE_MGR_PORT
          value: "7690"
        - name: GAME_WORLD_ID
          value: "{{ .Values.GameWorldId }}"
        - name: GLOBALCOPYMAP_ID
          value: "{{ .Values.GlobalcopymapId }}"
        - name: GMTOOL_SKIP
          value: "1"
        - name: GMTOOL_SERVER_HOST
          value: "gmtool"
        - name: GMTOOL_SERVER_PORT
          value: "3344"
        - name: REDIS_WORLD_HOST
          value: "redis"
        - name: REDIS_WORLD_PORT
          value: "6379"
        - name: REDIS_GLOBAL_HOST
          value: "{{ .Values.RedisGlobalHost }}"
        - name: REDIS_GLOBAL_PORT
          value: "6379"
        volumeMounts:
        - name: config
          mountPath: "/config"
        resources:
          requests:
{{- if eq .Values.env "prod" }}
            cpu: 1000m
            memory: 5Gi
{{- else }}
            cpu: 500m
            memory: 2Gi
{{- end }}
        ports:
        - containerPort: 1339
        - containerPort: 8001
      priorityClassName: common-priority
      nodeSelector:
        name: {{ .Values.NodeSelectorName }}
      volumes:
      - name: config
        secret:
          secretName: config
