apiVersion: apps/v1
kind: Deployment
metadata:
  name: copymap
spec:
  selector:
    matchLabels:
      app: copymap
      tier: backend
  revisionHistoryLimit: 5
{{- if eq .Values.env "prod" }}
  replicas: 3
{{- else }}
  replicas: 2
{{- end }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: copymap
        tier: backend
    spec:
      containers:
      - name: copymap
        image: {{ .Values.FirestrikeServerDockerImage }}
        env:
        - name: SERVER_TYPE
          value: "copymap"
        - name: COPYMAP_LISTEN_PORT
          value: "1342"
        - name: NODE_MGR_HOST
          value: "{{ .Values.NodemgrHost }}"
        - name: NODE_MGR_PORT
          value: "7690"
        - name: GLOBALCOPYMAP_ID
          value: "{{ .Values.GlobalcopymapId }}"
        - name: REDIS_COPYMAP_HOST
          value: "redis"
        - name: REDIS_COPYMAP_PORT
          value: "6379"
        - name: COPYMAP_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: config
          mountPath: "/config"
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
        ports:
        - containerPort: 1342
        - containerPort: 8001
      priorityClassName: common-priority
      nodeSelector:
        name: {{ .Values.NodeSelectorName }}
      volumes:
      - name: config
        secret:
          secretName: config
