apiVersion: apps/v1
kind: Deployment
metadata:
  name: center
spec:
  selector:
    matchLabels:
      app: center
  revisionHistoryLimit: 5
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: center
    spec:
      containers:
      - name: center
        image: {{ .Values.FirestrikeServerDockerImage }}
        env:
        - name: SERVER_TYPE
          value: "center"
        - name: CENTER_LISTEN_PORT
          value: "1338"
        - name: NODE_MGR_HOST
          value: "{{ .Values.NodemgrHost }}"
        - name: NODE_MGR_PORT
          value: "7690"
        - name: GAME_WORLD_ID
          value: "{{ .Values.GameWorldId }}"
        - name: NODE_LISTEN_PORT
          value: "1337"
        - name: REDIS_WORLD_HOST
          value: "redis"
        - name: REDIS_WORLD_PORT
          value: "6379"
        - name: REDIS_GLOBAL_HOST
          value: "{{ .Values.RedisGlobalHost }}"
        - name: REDIS_GLOBAL_PORT
          value: "6379"
        volumeMounts:
        - name: config
          mountPath: "/config"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 1337
        - containerPort: 1338
        - containerPort: 8001
      priorityClassName: common-priority
      nodeSelector:
        name: {{ .Values.NodeSelectorName }}
      volumes:
      - name: config
        secret:
          secretName: config
