apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: master
        image: redis:6.2  # or just image: redis
        command: ["redis-server", "/conf/redis.conf"]
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: conf
          mountPath: /conf
          readOnly: false
        - name: data
          mountPath: /data
          readOnly: false
      volumes:
      - name: conf
        configMap:
          name: redis-configmap
      priorityClassName: common-priority
      nodeSelector:
        name: {{ .Values.NodeSelectorName }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 16Gi
